//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Header
    {
        public int ID { get; set; }
        public string ImagerHeader { get; set; }
        public Nullable<int> IDProdcut { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsSlider { get; set; }
        public bool IsBanner { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
