//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ConnectionStringDBShop : DbContext
    {
        public ConnectionStringDBShop()
            : base("name=ConnectionStringDBShop")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Header> Headers { get; set; }
        public virtual DbSet<Introduction> Introductions { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<SupportFeature> SupportFeatures { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
    
        public virtual int ADD_CATEGORY(string nameCategory, string imageCategory)
        {
            var nameCategoryParameter = nameCategory != null ?
                new ObjectParameter("NameCategory", nameCategory) :
                new ObjectParameter("NameCategory", typeof(string));
    
            var imageCategoryParameter = imageCategory != null ?
                new ObjectParameter("ImageCategory", imageCategory) :
                new ObjectParameter("ImageCategory", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADD_CATEGORY", nameCategoryParameter, imageCategoryParameter);
        }
    
        public virtual int DELETE_CATEGORY(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETE_CATEGORY", iDParameter);
        }
    
        public virtual int EDIT_CATEGORY(Nullable<int> iD, string nameCategory, string imageCategory)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var nameCategoryParameter = nameCategory != null ?
                new ObjectParameter("NameCategory", nameCategory) :
                new ObjectParameter("NameCategory", typeof(string));
    
            var imageCategoryParameter = imageCategory != null ?
                new ObjectParameter("ImageCategory", imageCategory) :
                new ObjectParameter("ImageCategory", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EDIT_CATEGORY", iDParameter, nameCategoryParameter, imageCategoryParameter);
        }
    
        public virtual ObjectResult<FIND_PRODUCT_Result> FIND_PRODUCT(string key)
        {
            var keyParameter = key != null ?
                new ObjectParameter("key", key) :
                new ObjectParameter("key", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FIND_PRODUCT_Result>("FIND_PRODUCT", keyParameter);
        }
    
        public virtual ObjectResult<GET_HEADER_Result> GET_HEADER()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_HEADER_Result>("GET_HEADER");
        }
    
        public virtual ObjectResult<GET_INFO_WEBSITE_Result> GET_INFO_WEBSITE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_INFO_WEBSITE_Result>("GET_INFO_WEBSITE");
        }
    
        public virtual ObjectResult<GET_INTRODUCTION_Result> GET_INTRODUCTION()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_INTRODUCTION_Result>("GET_INTRODUCTION");
        }
    
        public virtual ObjectResult<GET_LIST_BANNER_IMG_Result> GET_LIST_BANNER_IMG()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_LIST_BANNER_IMG_Result>("GET_LIST_BANNER_IMG");
        }
    
        public virtual ObjectResult<GET_LIST_SLIDER_IMG_Result> GET_LIST_SLIDER_IMG()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_LIST_SLIDER_IMG_Result>("GET_LIST_SLIDER_IMG");
        }
    
        public virtual ObjectResult<GET_PRODUCT_BY_CATEGORY_Result> GET_PRODUCT_BY_CATEGORY(Nullable<int> iDCategory, Nullable<int> pAGE)
        {
            var iDCategoryParameter = iDCategory.HasValue ?
                new ObjectParameter("IDCategory", iDCategory) :
                new ObjectParameter("IDCategory", typeof(int));
    
            var pAGEParameter = pAGE.HasValue ?
                new ObjectParameter("PAGE", pAGE) :
                new ObjectParameter("PAGE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_PRODUCT_BY_CATEGORY_Result>("GET_PRODUCT_BY_CATEGORY", iDCategoryParameter, pAGEParameter);
        }
    
        public virtual ObjectResult<GETLISTCATEGORY_Result> GETLISTCATEGORY()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GETLISTCATEGORY_Result>("GETLISTCATEGORY");
        }
    
        public virtual ObjectResult<GETLISTPRODUCT_INTEREST_Result> GETLISTPRODUCT_INTEREST()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GETLISTPRODUCT_INTEREST_Result>("GETLISTPRODUCT_INTEREST");
        }
    
        public virtual ObjectResult<GETLISTPRODUCT_PRICESALE_Result> GETLISTPRODUCT_PRICESALE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GETLISTPRODUCT_PRICESALE_Result>("GETLISTPRODUCT_PRICESALE");
        }
    
        public virtual ObjectResult<GETLISTPRODUCT_SELLMAX_Result> GETLISTPRODUCT_SELLMAX()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GETLISTPRODUCT_SELLMAX_Result>("GETLISTPRODUCT_SELLMAX");
        }
    
        public virtual ObjectResult<GETNEWS_BY_DATE_Result> GETNEWS_BY_DATE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GETNEWS_BY_DATE_Result>("GETNEWS_BY_DATE");
        }
    
        public virtual ObjectResult<GETNEWS_BY_VIEW_Result> GETNEWS_BY_VIEW()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GETNEWS_BY_VIEW_Result>("GETNEWS_BY_VIEW");
        }
    
        public virtual ObjectResult<GETNEWSDETAIL_Result> GETNEWSDETAIL(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GETNEWSDETAIL_Result>("GETNEWSDETAIL", iDParameter);
        }
    
        public virtual ObjectResult<GETPRODUCT_BY_TYPE_DATE_ASC_Result> GETPRODUCT_BY_TYPE_DATE_ASC(Nullable<int> pAGE)
        {
            var pAGEParameter = pAGE.HasValue ?
                new ObjectParameter("PAGE", pAGE) :
                new ObjectParameter("PAGE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GETPRODUCT_BY_TYPE_DATE_ASC_Result>("GETPRODUCT_BY_TYPE_DATE_ASC", pAGEParameter);
        }
    
        public virtual ObjectResult<GETPRODUCT_BY_TYPE_PRICE_ASC_Result> GETPRODUCT_BY_TYPE_PRICE_ASC(Nullable<int> pAGE)
        {
            var pAGEParameter = pAGE.HasValue ?
                new ObjectParameter("PAGE", pAGE) :
                new ObjectParameter("PAGE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GETPRODUCT_BY_TYPE_PRICE_ASC_Result>("GETPRODUCT_BY_TYPE_PRICE_ASC", pAGEParameter);
        }
    
        public virtual ObjectResult<GETPRODUCT_BY_TYPE_PRICE_DESC_Result> GETPRODUCT_BY_TYPE_PRICE_DESC(Nullable<int> pAGE)
        {
            var pAGEParameter = pAGE.HasValue ?
                new ObjectParameter("PAGE", pAGE) :
                new ObjectParameter("PAGE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GETPRODUCT_BY_TYPE_PRICE_DESC_Result>("GETPRODUCT_BY_TYPE_PRICE_DESC", pAGEParameter);
        }
    
        public virtual ObjectResult<GETPRODUCT_NEWS_Result> GETPRODUCT_NEWS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GETPRODUCT_NEWS_Result>("GETPRODUCT_NEWS");
        }
    
        public virtual ObjectResult<GETPRODUCTALL_Result> GETPRODUCTALL(Nullable<int> pAGE)
        {
            var pAGEParameter = pAGE.HasValue ?
                new ObjectParameter("PAGE", pAGE) :
                new ObjectParameter("PAGE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GETPRODUCTALL_Result>("GETPRODUCTALL", pAGEParameter);
        }
    
        public virtual ObjectResult<GETPRODUCTDETAIL_BY_ID_Result> GETPRODUCTDETAIL_BY_ID(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GETPRODUCTDETAIL_BY_ID_Result>("GETPRODUCTDETAIL_BY_ID", iDParameter);
        }
    
        public virtual int ADD_NEWS(string nameNews, Nullable<int> iDCreater, Nullable<System.DateTime> date, string imageNews, string imageNewDetail, Nullable<int> viewMax, string descriptionNews)
        {
            var nameNewsParameter = nameNews != null ?
                new ObjectParameter("NameNews", nameNews) :
                new ObjectParameter("NameNews", typeof(string));
    
            var iDCreaterParameter = iDCreater.HasValue ?
                new ObjectParameter("IDCreater", iDCreater) :
                new ObjectParameter("IDCreater", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            var imageNewsParameter = imageNews != null ?
                new ObjectParameter("ImageNews", imageNews) :
                new ObjectParameter("ImageNews", typeof(string));
    
            var imageNewDetailParameter = imageNewDetail != null ?
                new ObjectParameter("ImageNewDetail", imageNewDetail) :
                new ObjectParameter("ImageNewDetail", typeof(string));
    
            var viewMaxParameter = viewMax.HasValue ?
                new ObjectParameter("ViewMax", viewMax) :
                new ObjectParameter("ViewMax", typeof(int));
    
            var descriptionNewsParameter = descriptionNews != null ?
                new ObjectParameter("DescriptionNews", descriptionNews) :
                new ObjectParameter("DescriptionNews", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADD_NEWS", nameNewsParameter, iDCreaterParameter, dateParameter, imageNewsParameter, imageNewDetailParameter, viewMaxParameter, descriptionNewsParameter);
        }
    
        public virtual int DELETE_NEWS(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETE_NEWS", iDParameter);
        }
    
        public virtual int EDIT_NEWS(Nullable<int> iD, string nameNews, Nullable<int> iDCreater, Nullable<System.DateTime> date, string imageNews, string imageNewDetail, Nullable<int> viewMax, string descriptionNews)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var nameNewsParameter = nameNews != null ?
                new ObjectParameter("NameNews", nameNews) :
                new ObjectParameter("NameNews", typeof(string));
    
            var iDCreaterParameter = iDCreater.HasValue ?
                new ObjectParameter("IDCreater", iDCreater) :
                new ObjectParameter("IDCreater", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            var imageNewsParameter = imageNews != null ?
                new ObjectParameter("ImageNews", imageNews) :
                new ObjectParameter("ImageNews", typeof(string));
    
            var imageNewDetailParameter = imageNewDetail != null ?
                new ObjectParameter("ImageNewDetail", imageNewDetail) :
                new ObjectParameter("ImageNewDetail", typeof(string));
    
            var viewMaxParameter = viewMax.HasValue ?
                new ObjectParameter("ViewMax", viewMax) :
                new ObjectParameter("ViewMax", typeof(int));
    
            var descriptionNewsParameter = descriptionNews != null ?
                new ObjectParameter("DescriptionNews", descriptionNews) :
                new ObjectParameter("DescriptionNews", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EDIT_NEWS", iDParameter, nameNewsParameter, iDCreaterParameter, dateParameter, imageNewsParameter, imageNewDetailParameter, viewMaxParameter, descriptionNewsParameter);
        }
    
        public virtual int DELETE_ROLES(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETE_ROLES", iDParameter);
        }
    
        public virtual ObjectResult<GET_LIST_ROLE_Result> GET_LIST_ROLE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_LIST_ROLE_Result>("GET_LIST_ROLE");
        }
    
        public virtual int INSERT_ROLES(string rOLENAME)
        {
            var rOLENAMEParameter = rOLENAME != null ?
                new ObjectParameter("ROLENAME", rOLENAME) :
                new ObjectParameter("ROLENAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_ROLES", rOLENAMEParameter);
        }
    
        public virtual int UPDATE_ROLES(Nullable<int> iD, string rOLENAME)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var rOLENAMEParameter = rOLENAME != null ?
                new ObjectParameter("ROLENAME", rOLENAME) :
                new ObjectParameter("ROLENAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_ROLES", iDParameter, rOLENAMEParameter);
        }
    
        public virtual int DELETE_CUSTOMER(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETE_CUSTOMER", iDParameter);
        }
    
        public virtual ObjectResult<GET_LIST_CUSTOMERS_Result> GET_LIST_CUSTOMERS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_LIST_CUSTOMERS_Result>("GET_LIST_CUSTOMERS");
        }
    
        public virtual int INSERT_CUSTOMER(string telephone, string userName, string password, string nameCustomer, Nullable<int> roleID)
        {
            var telephoneParameter = telephone != null ?
                new ObjectParameter("Telephone", telephone) :
                new ObjectParameter("Telephone", typeof(string));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var nameCustomerParameter = nameCustomer != null ?
                new ObjectParameter("NameCustomer", nameCustomer) :
                new ObjectParameter("NameCustomer", typeof(string));
    
            var roleIDParameter = roleID.HasValue ?
                new ObjectParameter("RoleID", roleID) :
                new ObjectParameter("RoleID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_CUSTOMER", telephoneParameter, userNameParameter, passwordParameter, nameCustomerParameter, roleIDParameter);
        }
    
        public virtual int UPDATE_CUSTOMER(Nullable<int> iD, string telephone, string userName, string password, string nameCustomer, Nullable<int> roleID)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var telephoneParameter = telephone != null ?
                new ObjectParameter("Telephone", telephone) :
                new ObjectParameter("Telephone", typeof(string));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var nameCustomerParameter = nameCustomer != null ?
                new ObjectParameter("NameCustomer", nameCustomer) :
                new ObjectParameter("NameCustomer", typeof(string));
    
            var roleIDParameter = roleID.HasValue ?
                new ObjectParameter("RoleID", roleID) :
                new ObjectParameter("RoleID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_CUSTOMER", iDParameter, telephoneParameter, userNameParameter, passwordParameter, nameCustomerParameter, roleIDParameter);
        }
    
        public virtual ObjectResult<GET_NEWS_ALL_Result> GET_NEWS_ALL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_NEWS_ALL_Result>("GET_NEWS_ALL");
        }
    
        public virtual int DETELET_PRODUCT(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DETELET_PRODUCT", iDParameter);
        }
    
        public virtual ObjectResult<GET_LISTPRODUCT_ALL_Result> GET_LISTPRODUCT_ALL(Nullable<int> pAGE)
        {
            var pAGEParameter = pAGE.HasValue ?
                new ObjectParameter("PAGE", pAGE) :
                new ObjectParameter("PAGE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_LISTPRODUCT_ALL_Result>("GET_LISTPRODUCT_ALL", pAGEParameter);
        }
    
        public virtual int INSERT_PRODUCT(string nameProduct, Nullable<decimal> price, string briefDes, string description, string imageProduct, string imageProductDetail1, string imageProductDetail2, Nullable<int> amount, Nullable<int> iDCategory, Nullable<decimal> priceSale, Nullable<int> interestProduct, Nullable<int> sellMax)
        {
            var nameProductParameter = nameProduct != null ?
                new ObjectParameter("NameProduct", nameProduct) :
                new ObjectParameter("NameProduct", typeof(string));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("Price", price) :
                new ObjectParameter("Price", typeof(decimal));
    
            var briefDesParameter = briefDes != null ?
                new ObjectParameter("BriefDes", briefDes) :
                new ObjectParameter("BriefDes", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var imageProductParameter = imageProduct != null ?
                new ObjectParameter("ImageProduct", imageProduct) :
                new ObjectParameter("ImageProduct", typeof(string));
    
            var imageProductDetail1Parameter = imageProductDetail1 != null ?
                new ObjectParameter("ImageProductDetail1", imageProductDetail1) :
                new ObjectParameter("ImageProductDetail1", typeof(string));
    
            var imageProductDetail2Parameter = imageProductDetail2 != null ?
                new ObjectParameter("ImageProductDetail2", imageProductDetail2) :
                new ObjectParameter("ImageProductDetail2", typeof(string));
    
            var amountParameter = amount.HasValue ?
                new ObjectParameter("Amount", amount) :
                new ObjectParameter("Amount", typeof(int));
    
            var iDCategoryParameter = iDCategory.HasValue ?
                new ObjectParameter("IDCategory", iDCategory) :
                new ObjectParameter("IDCategory", typeof(int));
    
            var priceSaleParameter = priceSale.HasValue ?
                new ObjectParameter("PriceSale", priceSale) :
                new ObjectParameter("PriceSale", typeof(decimal));
    
            var interestProductParameter = interestProduct.HasValue ?
                new ObjectParameter("InterestProduct", interestProduct) :
                new ObjectParameter("InterestProduct", typeof(int));
    
            var sellMaxParameter = sellMax.HasValue ?
                new ObjectParameter("SellMax", sellMax) :
                new ObjectParameter("SellMax", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_PRODUCT", nameProductParameter, priceParameter, briefDesParameter, descriptionParameter, imageProductParameter, imageProductDetail1Parameter, imageProductDetail2Parameter, amountParameter, iDCategoryParameter, priceSaleParameter, interestProductParameter, sellMaxParameter);
        }
    
        public virtual int UPDATE_PRODUCT(Nullable<int> iD, string nameProduct, Nullable<decimal> price, string briefDes, string description, string imageProduct, string imageProductDetail1, string imageProductDetail2, Nullable<int> amount, Nullable<int> iDCategory, Nullable<decimal> priceSale, Nullable<int> interestProduct, Nullable<int> sellMax)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var nameProductParameter = nameProduct != null ?
                new ObjectParameter("NameProduct", nameProduct) :
                new ObjectParameter("NameProduct", typeof(string));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("Price", price) :
                new ObjectParameter("Price", typeof(decimal));
    
            var briefDesParameter = briefDes != null ?
                new ObjectParameter("BriefDes", briefDes) :
                new ObjectParameter("BriefDes", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var imageProductParameter = imageProduct != null ?
                new ObjectParameter("ImageProduct", imageProduct) :
                new ObjectParameter("ImageProduct", typeof(string));
    
            var imageProductDetail1Parameter = imageProductDetail1 != null ?
                new ObjectParameter("ImageProductDetail1", imageProductDetail1) :
                new ObjectParameter("ImageProductDetail1", typeof(string));
    
            var imageProductDetail2Parameter = imageProductDetail2 != null ?
                new ObjectParameter("ImageProductDetail2", imageProductDetail2) :
                new ObjectParameter("ImageProductDetail2", typeof(string));
    
            var amountParameter = amount.HasValue ?
                new ObjectParameter("Amount", amount) :
                new ObjectParameter("Amount", typeof(int));
    
            var iDCategoryParameter = iDCategory.HasValue ?
                new ObjectParameter("IDCategory", iDCategory) :
                new ObjectParameter("IDCategory", typeof(int));
    
            var priceSaleParameter = priceSale.HasValue ?
                new ObjectParameter("PriceSale", priceSale) :
                new ObjectParameter("PriceSale", typeof(decimal));
    
            var interestProductParameter = interestProduct.HasValue ?
                new ObjectParameter("InterestProduct", interestProduct) :
                new ObjectParameter("InterestProduct", typeof(int));
    
            var sellMaxParameter = sellMax.HasValue ?
                new ObjectParameter("SellMax", sellMax) :
                new ObjectParameter("SellMax", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_PRODUCT", iDParameter, nameProductParameter, priceParameter, briefDesParameter, descriptionParameter, imageProductParameter, imageProductDetail1Parameter, imageProductDetail2Parameter, amountParameter, iDCategoryParameter, priceSaleParameter, interestProductParameter, sellMaxParameter);
        }
    }
}
