//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int ID { get; set; }
        public string NameNews { get; set; }
        public Nullable<int> IDCreater { get; set; }
        public System.DateTime Date { get; set; }
        public string ImageNews { get; set; }
        public string ImageNewDetail { get; set; }
        public Nullable<int> ViewMax { get; set; }
        public string DescriptionNews { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
