//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Headers = new HashSet<Header>();
        }
    
        public int ID { get; set; }
        public string NameProduct { get; set; }
        public decimal Price { get; set; }
        public string BriefDes { get; set; }
        public string Description { get; set; }
        public string ImageProduct { get; set; }
        public string ImageProductDetail1 { get; set; }
        public string ImageProductDetail2 { get; set; }
        public int Amount { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> IDCategory { get; set; }
        public Nullable<decimal> PriceSale { get; set; }
        public Nullable<int> InterestProduct { get; set; }
        public Nullable<int> SellMax { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Header> Headers { get; set; }
    }
}
